---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibonacci-deployment
  namespace: fibonacci-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: fibonacci-pod
  template:
    metadata:
      labels:
        pod: fibonacci-pod
    spec:
      containers:
        - name: fibonacci
          image: quay.io/colemanx/fibonacci:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
...
